### ISSUE TITLE
i.MXRT1050 project compiles but does not start, I2C issue(?)

### ISSUE THREAD

**Issue by marcin-ch** [marcin-ch/rt1050_emwin#1]
# Problem description
When you uncomment the code:

`I2C i2c(I2C_SDA, I2C_SCL);`

in

`MLX90640\MLX90640_I2C_Driver.cpp`

then project still is able to compile, unfortunately i.MXRT1050 eval board does not start.

Most likely the issue refers to code:

`BOARD_InitI2C1Pins();`

in

`source\main.cpp`

as both pieces of code:

`I2C i2c(I2C_SDA, I2C_SCL);`

and

`BOARD_InitI2C1Pins();`

refer to signals
`GPIO_AD_B1_00` and `GPIO_AD_B1_01`

So I believe this is the point which causes problems.
Any hints how to sort it out?
@maclobdell

**Comment by linlingao** [comment]
@marcin-ch Thanks for setting up the project. I have the MIMXRT1050-EVK and the LCD board. I'll need to get the MLX90640 to test I2C. Can you send me a link to the MLX90640 board you're using?

**Comment by marcin-ch** [comment]
@linlingao please have a look at documentation for [MLX90640](https://www.melexis.com/en/product/MLX90640/Far-Infrared-Thermal-Sensor-Array).
The sensor has only 4 pins: Vdd, GND, SCL, SDA.
I believe you do not need to look exactly for this sensor, you can use any with **I2C** interface (**just to check if you are able to talk to I2C device connected to Arduino connectors when emWin is also on the board**).
Hope, for example I2C temperature sensor from **Components** you have libraries available at [os.mbed.com/components](https://os.mbed.com/components/MLX90614-I2C-Infrared-Thermometer/) you have available from the shelf and ready for tests.

Please be aware of little hardware changes required for i.MXRT1050 eval board described in [Important Notes](https://os.mbed.com/platforms/MIMXRT1050-EVK/), so it means:
`The I2C signals connected to D14 & D15 on the Arduino header are not capable of I2C Master mode. To use the I2C master mode with an Arduino-compatible shield slave such as a memory shield, connect D14 (SDA) to A4 and D15 (SCL) to A5`

**Comment by linlingao** [comment]
@marcin-ch Thanks for the suggestions. I have a test shield with I2C slave I can try.
I'm currently having trouble with pyOCD on this board. It's a known issue that pyOCD doesn't work on this target. What debugger are you using?

**Comment by marcin-ch** [comment]
@linlingao I experienced problems with pyOCD as well, however please double-check this [note](https://github.com/mbedmicro/pyOCD#libusb-installation).
Especially:
`Windows: download libusb from libusb.info and place the DLL in your Python installation folder next to python.exe`
Anyway, it does not work for me.

What's more, I followed this [guide for Visual Code Studio](https://os.mbed.com/docs/mbed-os/v5.11/tutorials/visual-studio-code.html) for debugging with VSC but finally I do not have debugging capabilities up and running.

I have also tried to export example project for i.MXRT1050 from Online Compiler to Keil based on this [guide](https://os.mbed.com/docs/mbed-os/v5.11/tutorials/keil-uvision.html) but I experienced a lot of errors, for example with scatter file similar to this [one](https://os.mbed.com/forum/bugs-suggestions/topic/33465/). Unfortunatelly, fixing this bug caused that other ones come up.

Summarize, I am open to the tools you can suggest to work with MBED OS as smooth as possible. Hope you can suggest something reliable and just working.

**Comment by linlingao** [comment]
@marcin-ch I got pyOCD to attach the debugger. My debug procedure is still cumbersome: I use DAPLink drag-n-drop to program the target flash (since pyOCD flash programming isn't working on this target), then use pyOCD to attach the debugger. I'll see if this can be improved.
I did get a pin map error when I tried to access my I2C slave (EEPROM) with LCD on at the same time, not sure if it's the same failure though.

**Comment by marcin-ch** [comment]
@linlingao I do also use DAPLink to drag-n-drop to flash the target.
`mbedls` command gives as follows
![imxrt1050_daplink](https://raw.githubusercontent.com/marcin-ch/issue_images/master/i.MXRT1050_I2C/imxrt1050_daplink.PNG)

`pyocd --version` command gives `0.14.0`

As you wrote:
> I did get a pin map error when I tried to access my I2C slave (EEPROM) with LCD on at the same time, not sure if it's the same failure though.

**I believe it could be the the same.** Unfortunately, I can not confirm that as I do not have debugging capabilities so far. When I try to run `I2C i2c(I2C_SDA, I2C_SCL);` **project still compiles** giving `*.bin` file (no errors coming from MBED CLI), I can flash the target with drag-n-drop method, but finally board does not start.

My workflow with MBED CLI is as follows:
`mbed target MIMXRT1050_EVK`
`mbed toolchain GCC_ARM`
`mbed compile`
drag-n-drop to target device
reset the board
nothing happens

So, any ideas how to address the error you experience and which could be the issue?

**Comment by linlingao** [comment]
I found the issue. The pin definitions for D14 and D15 are wrong. Try the following fix. I can write to and read from Eeprom on the I2C bus now with LCD enabled with this change.

C02W4129HV2T:mbed-os lingao01$ git diff
diff --git a/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h b/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
index 90212569e3..c52089dd3c 100644
--- a/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
+++ b/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
@@ -193,8 +193,8 @@ typedef enum {
     D11 = GPIO_SD_B0_02,
     D12 = GPIO_SD_B0_03,
     D13 = GPIO_SD_B0_00,
-    D14 = GPIO_AD_B0_01,
-    D15 = GPIO_AD_B0_00,
+    D14 = GPIO_AD_B1_01,
+    D15 = GPIO_AD_B1_00,
 
     I2C_SCL = D15,
     I2C_SDA = D14,

**Comment by linlingao** [comment]
@marcin-ch Let me know if this fixes your issue with the thermal camera. If not, I'll need to order the part.

**Comment by linlingao** [comment]
@marcin-ch Github site displays bullet points instead of - and +. The change is to replace D14 and D15 definition with
D14 = GPIO_AD_B1_01,
D15 = GPIO_AD_B1_00,

**Comment by linlingao** [comment]
@marcin-ch I checked in the code to https://github.com/linlingao/rt1050_emwin/tree/fix_pinmap to exercise the I2C Eeprom on CI test shield for your reference.
https://github.com/ARMmbed/mbed-HDK/tree/master/Production%20Design%20Projects/ARM-mbed/CITestShield

**Comment by marcin-ch** [comment]
@linlingao fist attempts after changing pin definitions for D14 and D15 are very promising and successful. I will keep testing this solution.

In the meantime, you wrote:
> My debug procedure is still cumbersome: I use DAPLink drag-n-drop to program the target flash (since pyOCD flash programming isn't working on this target), **then use pyOCD to attach the debugger**. I'll see if this can be improved.

what is your workflow with pyOCD? could you advise what are the steps when using pyOCD to attach the debugger?

> I did get a pin map error when I tried to access my I2C slave (EEPROM) with LCD on at the same time, not sure if it's the same failure though.

Is that error you got during compilation? after invoking `mbed compile`? I am asking because, as I said before, I did not get any compilation errors during compilation, however program did not work. So this error seemed to be very helpful and descriptive when looking for solution.

**Comment by linlingao** [comment]
I use pyOCD in Eclipse for debug. To attach the target without programing flash, in Debug Configurations, create a GDB PyOCD Debugging, give a project name. Click Startup tab, uncheck Initial Reset and Load executable. I also uncheck Pre-run, Restart reset. Click Apply then Debug.
If you have SEGGER JLink debugger, I think it'll work. I haven't got access to a JLink so I haven't tried it.
The pin map error was runtime error/crash. It was fixed after applying the fixes. I didn't have compilation errors.

**Comment by linlingao** [comment]
@marcin-ch Just wanted to see if you're able to make progress with the steps I provided to attach the debugger without programming the target.
Do you have other issues that gate you?

**Comment by marcin-ch** [comment]
@linlingao as I said before, changing pin definitions for D14 and D15 allowed me to make further steps with the project so thank you very much for finding solution for this issue.
Unfortunately, when adding to project further calculations, for example *Extract calibration data from EEPROM and store in RAM* as decribed in datasheet for [MLX90640](https://www.melexis.com/en/product/MLX90640/Far-Infrared-Thermal-Sensor-Array) the project just hangs and nothing happens.

What I noticed from Online Compiler, the usage of RAM is more than it really exists, please see attached
![imxrt1050_emwin_online_compiler](https://raw.githubusercontent.com/marcin-ch/issue_images/master/i.MXRT1050_I2C/imxrt1050_emwin_online_compiler.PNG)
It refers to project when only emWin on i.MXRT1050 is runing without any communication to sensor.

So I am wonder if adding some further calculations causes the project just hangs.
Or it is just some bug and Online Compiler presents usage of RAM 4.2MB when i.MXRT1050 supports only 0.5MB?

What is more, similar thing I can see using MBED CLI:
`Total Static RAM memory (data + bss): 4271352 bytes`

Could you please double-check how it looks like on your side?

**Comment by linlingao** [comment]
I imported the mbed-os-example-blinky example. The RAM usage is only 105.5KB.
It looks like your program uses 4.2MB ZI data. This is way too big. You should be able to tell from the map file where the bug is. The map file is generated and located in the BUILD directory if you use MBED CLI. I don't expect your program to run unless the RAM usage is reduced to less than 512KB.

**Comment by marcin-ch** [comment]
@linlingao yes, for *mbed-os-example-blinky example* that is true, but please double-check how the things are going in my project. Below you can find what I can see from MBED CLI:

![imxrt1050_emwin_MBED_CLI](https://raw.githubusercontent.com/marcin-ch/issue_images/master/i.MXRT1050_I2C/imxrt1050_emwin_MBED_CLI.PNG)

As you have access to the code, please double-check on your side how it looks like.

What is more, I have this project using emWin up and running under MCUXpresso (let's say it is native tool for developing applications for NXP MCUs and does not use MBED OS).
What I did notice, the project uses additional SDRAM available on the i.MXRT1050 eval board (this memory is 32MB). Please have a look at statistics after compiling/linking from MCUXpresso:

![imxrt1050_emwin_mcuxpresso](https://raw.githubusercontent.com/marcin-ch/issue_images/master/i.MXRT1050_I2C/imxrt1050_emwin_mcuxpresso.PNG)

So perhaps, it is the possible solutions? How and where to change the configuration of the project tu use external SDRAM?

**Comment by linlingao** [comment]
I checked your project. It does use 4M RAM.
+------------------------+--------+-------+---------+
| Module                 |  .text | .data |    .bss |
+------------------------+--------+-------+---------+
| I2CEeprom/I2CEeprom.o  |    234 |     0 |       0 |
| [fill]                 |    217 |     4 |      23 |
| [lib]/c.a              |  30807 |  2472 |      89 |
| [lib]/emWin_M4F.a      |  35502 |    28 |    1549 |
| [lib]/gcc.a            |    768 |     0 |       0 |
| [lib]/misc             |    204 |     4 |      28 |
| [lib]/nosys.a          |     32 |     0 |       0 |
| [misc]                 |     16 |     0 |       0 |
| mbed-os/drivers        |   1441 |     0 |      44 |
| mbed-os/hal            |   1711 |     4 |      68 |
| mbed-os/platform       |   4421 |   260 |     217 |
| mbed-os/rtos           |   8916 |   168 |    6073 |
| mbed-os/targets        |  18619 |    44 |     505 |
| source/board.o         |    200 |     0 |       0 |
| source/emwin_support.o |    430 |     4 | 4257980 |
| source/fsl_ft5406_rt.o |    185 |     0 |       0 |
| source/main.o          |    525 |     0 |     104 |
| source/pin_mux.o       |    484 |     0 |       0 |
| Subtotals              | 104712 |  2988 | 4266680 |
+------------------------+--------+-------+---------+
Total Static RAM memory (data + bss): 4269668 bytes
Total Flash memory (text + data): 107700 bytes

I also checked the linker script, the external RAM is being used:
  m_data                (RW)  : ORIGIN = 0x80000000, LENGTH = 0x01E00000
  m_ncache           (RW)  : ORIGIN = 0x81E00000, LENGTH = 0x00200000

  .data : AT(__DATA_ROM)
  {
    . = ALIGN(8);
    __DATA_RAM = .;
    __data_start__ = .;      /* create a global symbol at data start */
    *(m_usb_dma_init_data)
    *(.data)                 /* .data sections */
    *(.data*)                /* .data* sections */
    KEEP(*(.jcr*))
    . = ALIGN(8);
    __data_end__ = .;        /* define a global symbol at data end */
  } > m_data

I don't see problem in RAM usage.

However, you did uncover an issue with the online compiler. The online compiler appears to be using the wrong value for available RAM. I'll raise an issue to get it fixed.

**Comment by maclobdell** [comment]
The online compiler references the internal SRAM size which is 512 KBytes.  Sounds like the internal and external total should be used.  I just made this update.  cc @mmahadevan108

**Comment by marcin-ch** [comment]
@linlingao please see updated project.
Project hangs when I try to invoke function in *main.cpp*
`MLX90640_ExtractParameters(eeMLX90640, &mlx90640);`

The console output is as follows:
```
GUI demo start.
Ready to go after Intro screen displayed
Time to dump EEPROM
```
and after that program just starts again.

As you do not have your own MLX90640 sensor, I have prepared EEPROM data so and no communication to sensor is needed. I just read EEPROM of my sensor and copied the data to table `eeMLX90640`.

Project compiles without errors. Could you please have a look?

**Comment by marcin-ch** [comment]
@linlingao the solution is to increase the stack.
To do that, add file called ***mbed_app.json*** in the root of the project and type the code:
```
{
    "config": {
        "thread_stack_size": {
            "value": 8192
        },
        "main_stack_size": {
            "value": 8192
        }
    }
}
```

Could be also important, to use compiling with debug symbols (as I had some artefacts on the display using `mbed compile`)
Based on [compiling using mbed cli with debug symbols](https://os.mbed.com/questions/74146/compiling-using-mbed-cli-with-debug-symb/) please compile using
`mbed compile --profile mbed-os/tools/profiles/debug.json`

**Comment by linlingao** [comment]
@marcin-ch Thanks for letting me know.
